version: "3.8"

services:
  opensearch:
    image: opensearchproject/opensearch:2.7.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      # Optionally disable security plugin for local testing.
      - plugins.security.disabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    restart: unless-stopped

  dashboards:
    image: opensearchproject/opensearch-dashboards:2.7.0
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    depends_on:
      - opensearch
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: tags_pg
    environment:
      POSTGRES_DB: tags_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build: ./app
    ports:
      - "8501:8501"
    depends_on:
      - opensearch
      - postgres
    volumes:
      - ./app:/app

  ui:
    build:
      context: ./lawsearch_ui
    ports:
      - "3000:8080"
    working_dir: /app
    volumes:
      - ./lawsearch_ui:/app
      - ui_node_modules:/app/node_modules/
    command: npm run dev
    depends_on:
      - app


volumes:
  opensearch-data:
  pg-data:
  ui_node_modules:
